services:
    server:
        container_name: server
        build:
            context: .
            target: server
        image: zkwordle:server
        network_mode: host

    client:
        container_name: client
        build:
            context: .
            target: client-dev
        image: zkwordle:client-dev
        depends_on:
            - server
        environment:
            REACT_APP_API_URL: http://localhost:3001/graphql
        network_mode: host
